version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - "./server:/server"
    command: npm run dev
    depends_on:
      - db_books
    networks:
      - books_net

  client:
    build:
      context: ./client
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - "./client:/client"
    networks:
      - books_net

  db_books:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_USER: oasis
      POSTGRES_DB: booksapp
    networks:
      - books_net

networks:
  books_net:
    driver: bridge
